let shopItemsData = [
    {
      id: "jfhgbvnscs1",
      name: "Adidas",
      price: 78,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/f1.jpg",
    },
    {
      id: "ioytrhndcv2",
      name: "Adidas",
      price: 100,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/f2.jpg",
    },
    {
      id: "wuefbncxbsn3",
      name: "T Shirt",
      price: 25,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/f3.jpg",
    },
    {
      id: "thyfhcbcv4",
      name: "Mens Suit",
      price: 300,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/f4.jpg",
    },
    {
      id: "jfhgbvnscs5",
      name: "Adidas",
      price: 78,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/f5.jpg",
    },
  {
      id: "ioytrhndcv6",
      name: "Adidas",
      price: 100,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/f6.jpg",
    },
  {
      id: "wuefbncxbsn7",
      name: "T Shirt",
      price: 25,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/f7.jpg",
    },
  {
      id: "thyfhcbcv8",
      name: "Mens Suit",
      price: 300,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/f8.jpg",
    },
    {
      id: "jfhgbvnscs9",
      name: "Adidas",
      price: 78,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/n1.jpg",
    },
  {
      id: "ioytrhndcv10",
      name: "Adidas",
      price: 100,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/n2.jpg",
    },
  {
      id: "wuefbncxbsn11",
      name: "T Shirt",
      price: 25,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/n3.jpg",
    },
  {
      id: "thyfhcbcv6612",
      name: "Mens Suit",
      price: 300,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/n4.jpg",
    },
    {
      id: "jfhgbvnscs13",
      name: "Adidas",
      price: 78,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/n5.jpg",
    },
  {
      id: "ioytrhndcv14",
      name: "Adidas",
      price: 100,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/n6.jpg",
    },
  {
      id: "wuefbncxbsn15",
      name: "T Shirt",
      price: 25,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/n7.jpg",
    },
  {
      id: "thyfhcbcv16",
      name: "Mens Suit",
      price: 300,
      desc: "Carton Astronaut T-shirts.",
      img: "img/products/n8.jpg",
    },
    ];
  